name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 4.7.2
    - name: Restore dependencies
      run: dotnet restore ./ShimmerAPI/ShimmerAPITest.sln
    - name: Build
      run: dotnet build ./ShimmerAPI/ShimmerAPITest.sln --no-restore
    - name: Test
      run: dotnet test ./ShimmerAPI/ShimmerAPITest.sln --no-build --verbosity normal
