name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1    
    - name: Restore dependencies
      run: dotnet restore ./ShimmerAPI/ShimmerAPITest.sln
    - name: Build
      run: dotnet build ./ShimmerAPI/ShimmerAPITest.sln --no-restore
    - name: Test
      run: dotnet test ./ShimmerAPI/ShimmerAPITest.sln --no-build --verbosity normal
