name: ShimmerBluetoothAPIUnitTest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2     
    - name: Build 
      run: msbuild ./ShimmerAPI/ShimmerAPITest.sln
    - name: Test
      run: msbuild test ./ShimmerAPI/ShimmerAPITest.sln --no-build --verbosity normal
    
