name: "Publish to NuGet"

on:
  push:
    branches:
      - CA-28_MA # Default release branch

env:
  PROJECT_PATH: 'ShimmerAPI/ShimmerAPI/ShimmerAPI.csproj'
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}\output
  NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'

jobs:
  deploy:
    name: 'Deploy'
    runs-on: 'windows-latest'
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

    - name: Restore NuGet packages
      run: nuget restore ShimmerAPI/ShimmerAPI.sln

    - name: Build Solution
      run: |
       msbuild.exe ShimmerAPI.sln /p:platform="Any CPU" /p:configuration="Release"

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
       name: ShimmerAPI
       path: "./_build"