name: ShimmerBLEAPIUnitTest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup dotnet
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: | 
         5.0.x
         2.0         
    - name: Restore dependencies
      run: dotnet restore ./ShimmerBLE/ShimmerBLEAPItest.sln
    - name: Delete PropertyChanged.Fody
      run: nuget delete PropertyChanged.Fody 2.6.1
    - name: Install PropertyChanged.Fody 3.4
      run: nuget install PropertyChanged.Fody -Version 3.4.0 -DirectDownload -OutputDirectory .
    - name: Build
      run: dotnet build ./ShimmerBLE/ShimmerBLEAPItest.sln --no-restore
    - name: Test
      run: dotnet test ./ShimmerBLE/ShimmerBLEAPItest.sln --no-build --verbosity normal
